[package]
name = "co_ast"
version = "0.1.0"
authors = ["lcnr <rust@lcnr.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
co_diag = { path = "../co_diag" }

tindex = { git = "https://github.com/lcnr/tindex/" }